"use strict";
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten
Object.defineProperty(exports, "__esModule", { value: true });
exports.onDeleteCoursesUsers = exports.onUpdateCoursesUsers = exports.onCreateCoursesUsers = exports.onDeleteCourse = exports.onUpdateCourse = exports.onCreateCourse = exports.onDeleteUser = exports.onUpdateUser = exports.onCreateUser = void 0;
exports.onCreateUser = "\n  subscription OnCreateUser($filter: ModelSubscriptionUserFilterInput) {\n    onCreateUser(filter: $filter) {\n      id\n      name\n      email\n      userType\n      courses {\n        items {\n          id\n          userId\n          courseId\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onUpdateUser = "\n  subscription OnUpdateUser($filter: ModelSubscriptionUserFilterInput) {\n    onUpdateUser(filter: $filter) {\n      id\n      name\n      email\n      userType\n      courses {\n        items {\n          id\n          userId\n          courseId\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onDeleteUser = "\n  subscription OnDeleteUser($filter: ModelSubscriptionUserFilterInput) {\n    onDeleteUser(filter: $filter) {\n      id\n      name\n      email\n      userType\n      courses {\n        items {\n          id\n          userId\n          courseId\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onCreateCourse = "\n  subscription OnCreateCourse($filter: ModelSubscriptionCourseFilterInput) {\n    onCreateCourse(filter: $filter) {\n      id\n      name\n      value\n      level\n      users {\n        items {\n          id\n          userId\n          courseId\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onUpdateCourse = "\n  subscription OnUpdateCourse($filter: ModelSubscriptionCourseFilterInput) {\n    onUpdateCourse(filter: $filter) {\n      id\n      name\n      value\n      level\n      users {\n        items {\n          id\n          userId\n          courseId\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onDeleteCourse = "\n  subscription OnDeleteCourse($filter: ModelSubscriptionCourseFilterInput) {\n    onDeleteCourse(filter: $filter) {\n      id\n      name\n      value\n      level\n      users {\n        items {\n          id\n          userId\n          courseId\n          createdAt\n          updatedAt\n        }\n        nextToken\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onCreateCoursesUsers = "\n  subscription OnCreateCoursesUsers(\n    $filter: ModelSubscriptionCoursesUsersFilterInput\n  ) {\n    onCreateCoursesUsers(filter: $filter) {\n      id\n      userId\n      courseId\n      user {\n        id\n        name\n        email\n        userType\n        courses {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      course {\n        id\n        name\n        value\n        level\n        users {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onUpdateCoursesUsers = "\n  subscription OnUpdateCoursesUsers(\n    $filter: ModelSubscriptionCoursesUsersFilterInput\n  ) {\n    onUpdateCoursesUsers(filter: $filter) {\n      id\n      userId\n      courseId\n      user {\n        id\n        name\n        email\n        userType\n        courses {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      course {\n        id\n        name\n        value\n        level\n        users {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
exports.onDeleteCoursesUsers = "\n  subscription OnDeleteCoursesUsers(\n    $filter: ModelSubscriptionCoursesUsersFilterInput\n  ) {\n    onDeleteCoursesUsers(filter: $filter) {\n      id\n      userId\n      courseId\n      user {\n        id\n        name\n        email\n        userType\n        courses {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      course {\n        id\n        name\n        value\n        level\n        users {\n          nextToken\n        }\n        createdAt\n        updatedAt\n      }\n      createdAt\n      updatedAt\n    }\n  }\n";
